exports.appName = 'thePomoAPP';	
exports.appId = 'thePomoAPPId';	

// Use your own Server Key as generated by Google Developer Console	
// For more details, see http://developer.android.com/google/gcm/gs.html	
exports.gcmServerApiKey = 'XXXXXX';	

exports.gcmSessionNew = 'session_new';	
exports.gcmSessionUpdated = 'session_updated';	
exports.gcmSessionDeleted = 'session_deleted';	
exports.gcmGroupAdded = 'group_added';	

exports.baseSettingId = 0;
